### ISSUE TITLE
Error Call to undefined method JApplicationAdministrator::setTemplate()

### ISSUE THREAD

**Issue by step-di** [Joomla-StackExchange/editorTemplate#2]
administrator form edit user in cck seblod :
/administrator/index.php?option=com_cck&view=form&return_o=users&return_v=users&type=user&id=
Error:
Call to undefined method JApplicationAdministrator::setTemplate()

\plugins\system\editortemplate\editortemplate.php
if ($view == 'form')  = > $url = $_SERVER['REQUEST_URI'];    if ($view == 'form' and !strpos($url,'administrator')  )

**Comment by C-Lodder** [comment]
Can you try this patch: https://github.com/Joomla-StackExchange/editorTemplate/pull/3

**Comment by step-di** [comment]
Call to undefined method JApplicationSite::isClient()

https://docs.joomla.org/Discover_on_which_client_your_extension_code_is_running/en
isClient() worked only joomla 3.7
J3.6 - isSite()

**Comment by C-Lodder** [comment]
What version of Joomla are you using?

**Comment by step-di** [comment]
Joomla! 3.6.5
if (!$app->isSite())	return;

**Comment by C-Lodder** [comment]
so `if (!$app->isSite()) return;` works?

**Comment by step-di** [comment]
Thank you for your responses. 
The problem with $ app-> setTemplate only occurs when using the Seblod component, in the user editor (the component defaults to editing the user in its form)

If (!$app->isSite()) return; 
Works in J3.6.5
but in Joomla 3.7 probably will not, will have to change to $app->isClient('site')
